FROM archlinux:latest

USER root
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Initialise pacman and fix makepkg
RUN pacman -Syu --noconfirm  && \
    sed -i 's/^[[:space:]]*exit \$E_ROOT/# exit \$E_ROOT/' "/usr/bin/makepkg"

# Install basic packages
# Install python and several packages we may need
# Install Octave dependencies
# Install Octave from official repos
RUN pacman -S --noconfirm --needed \
        base-devel \
        curl \
        ca-certificates \
        git \
        nano \
        tree && \
    pacman -S --noconfirm --needed \
        python \
        python-charset-normalizer \
        python-idna \
        python-pip \
        python-requests \
        python-urllib3 && \
    pacman -S --noconfirm --needed \
        arpack fftw fltk gcc-fortran glu glpk gperf graphicsmagick hdf5 \
        icoutils java-environment llvm mercurial pcre qhull qrupdate qscintilla-qt6 \
        qt6-base qt6-tools rapidjson rsync texinfo texlive-bin transfig gl2ps perl && \
    pacman -S --noconfirm --needed \
        octave

# Install units from AUR
RUN git clone https://aur.archlinux.org/units.git && \
    cd units && \
    makepkg -si --skippgpcheck --noconfirm && \
    cd .. && \
    rm -rf units

## Clean up pacman cache
RUN pacman -Scc --noconfirm

# Create group and user with fixed UID/GID
RUN groupadd -g 500 octave && \
    useradd -m -u 500 -g 500 -o -s /bin/bash octave

USER octave

WORKDIR /home/octave

COPY --from=scripts pkg_install.m /home/octave/pkg_install.m

RUN /usr/bin/octave /home/octave/pkg_install.m

ENV PS1="(octave) \\u@\\h:\\w\\$ "

# Entrypoint to start Octave
ENTRYPOINT ["/bin/bash"]
