FROM docker.io/gnuoctave/octave:latest

# ENV LANG=C.UTF-8
# ENV LC_ALL=C.UTF-8

ENV PS1="(octave) \\u@\\h:\\w\\$ "

# Entrypoint to start Octave
# ENTRYPOINT ["/bin/bash"]

# Ensure Octave runs purely in the terminal by default
CMD ["octave", "--no-gui", "--no-window-system"]
