FROM debian:stable

USER root
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Install Octave dependencies
RUN apt-get update && \
    apt-get install -yqq --no-install-recommends \
        apt-utils && \
    apt-get install -yqq \
        curl \
        ca-certificates \
        nano \
        python3 \
        python3-pip \
        tree

RUN apt-get install -yqq --no-install-recommends \
        octave \
        octave-doc \
        octave-statistics \

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create group and user with fixed UID/GID
RUN groupadd -g 500 octave
RUN useradd -m -u 500 -g 500 -o -s /bin/bash octave

USER octave
WORKDIR /home/octave
ENV PS1="(octave) \\u@\\h:\\w\\$ "

# Entrypoint to start Ollama
ENTRYPOINT ["/bin/bash"]
