FROM docker.io/rocm/pytorch:latest

# switch to `root` for easy installation
USER root

ENV DEBIAN_FRONTEND=noninteractive

# Install Ollama dependencies
RUN apt-get update && \
    apt-get install -yqq --no-install-recommends \
        apt-utils && \
    apt-get install -yqq \
        curl \
        ca-certificates \
        zstd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Ollama
RUN curl -fsSL https://ollama.ai/install.sh | sh

# Create a non-root user and group
# Create ollama group and user with fixed UID/GID
# remove ollama user and group and recreate them
RUN gpasswd -d root ollama &&\
    userdel ollama && \
    groupadd -g 500 ollama && \
    useradd -d /usr/share/ollama -u 500 -g 500 -o -s /bin/bash ollama && \
    usermod -aG render ollama && \
    usermod -aG video ollama && \
    usermod -aG ollama root && \
    chown -R ollama:ollama /usr/share/ollama

USER ollama
WORKDIR /usr/share/ollama
ENV PS1="(ollama-pytorch) \\u@\\h:\\w\\$ "

# ENV OLLAMA_CONTEXT_LENGTH=4096
ENV OLLAMA_HOST=0.0.0.0:11434
ENV OLLAMA_MODELS=/usr/share/ollama/.ollama/models
# ENV OLLAMA_NUM_PARALLEL=1
# We have gfx1103, but gfx1102 is the closest one and we need these:
ENV HSA_OVERRIDE_GFX_VERSION=11.0.2
ENV ROCM_TARGET=gfx1102
ENV GPU_ARCH=gfx1102

# Expose the Ollama API port
EXPOSE 11434

# RUN mkdir -p /home/ollama/.ollama

# Entrypoint to start Ollama
ENTRYPOINT ["ollama", "serve"]
