FROM docker.io/pihole/pihole:latest
# This is a ALPINE image

# Create a non-root user and group
# Create pihole group and user with fixed UID/GID
# remove pihole user and group and recreate them
RUN gpasswd -d pihole pihole &&\
    userdel pihole && \
    groupdel pihole; \
    groupadd -g 500 pihole && \
    useradd -d /home/pihole -u 500 -g 500 -o -s /bin/bash pihole


# Set timezone and upstream DNS servers
# (You can override these at runtime with -e or env files)
ENV TZ="Europe/Amsterdam" \
    FTLCONF_dns_upstreams="8.8.8.8;8.8.4.4;192.168.1.1" \
    FTLCONF_dns_listeningMode="ALL"

# Expose required ports
# DNS
EXPOSE 53/tcp
EXPOSE 53/udp
# HTTP / HTTPS
EXPOSE 80/tcp
EXPOSE 443/tcp
# DHCP
EXPOSE 67/udp
# Uncomment the line below if you are using Pi-hole as your NTP server
# EXPOSE 123/udp

USER pihole
#WORKDIR /home/pihole
