# Containerfile for lektrix/web:latest
FROM debian:stable
#-slim

ENV DEBIAN_FRONTEND=noninteractive

# Create directories expected by lighttpd & Install lighttpd
RUN mkdir -p /var/www/html && \
    apt-get update && \
    apt-get install -yqq --no-install-recommends \
        apt-utils && \
    apt-get install -yqq --no-install-recommends \
        lighttpd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Enable required modules and remove Debian's placeholder
RUN ln -s ../conf-available/10-dir-listing.conf /etc/lighttpd/conf-enabled/10-dir-listing.conf && \
    rm -f /etc/lighttpd/conf-enabled/99-unconfigured.conf

# Expose internal HTTP port
EXPOSE 80

# Entrypoint
CMD ["/usr/sbin/lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
