# Use a ROCm-enabled base image
FROM docker.io/rocm/rocm-terminal:latest
# switch to `root` for easy installation
USER root

# Install Ollama dependencies
RUN apt-get update && apt-get install -y \
    apt-utils \
    curl \
    ca-certificates \
    zstd \
    && rm -rf /var/lib/apt/lists/*

# create the `render` group which is needed for ROCm
RUN groupadd -r render

# Install Ollama
RUN curl -fsSL https://ollama.ai/install.sh | sh

# Create a non-root user and group
# Create ollama group and user with fixed UID/GID
RUN groupadd -g 500 ollama \
    && useradd -u 500 -g 500 -m -s /bin/bash ollama \
    && chown -R ollama:ollama /home/ollama

USER ollama
WORKDIR /home/ollama
ENV PS1="(ollama-rocm) \\u@\\h:\\w\\$ "

# ENV OLLAMA_CONTEXT_LENGTH=4096
ENV OLLAMA_HOST=0.0.0.0:11434
ENV OLLAMA_MODELS=/home/ollama/.ollama/models
# ENV OLLAMA_NUM_PARALLEL=1
# We have gfx1103, but gfx1102 is the closest one that is supported ATM
ENV HSA_OVERRIDE_GFX_VERSION=11.0.2
ENV ROCM_TARGET=gfx1102
ENV GPU_ARCH=gfx1102

# Expose the Ollama API port
EXPOSE 11434

# Volume for model storage (persistent across container restarts)
VOLUME /home/ollama/.ollama

# Entrypoint to start Ollama
ENTRYPOINT ["ollama", "serve"]

# Entrypoint to shell for testing
# ENTRYPOINT ["/bin/bash"]
