apiVersion: v1
kind: Pod
metadata:
  name: test12
  annotations:
    io.podman.annotations.network: slirp4netns
spec:
  containers:
  - name: test1
    image: helheim/test1:latest
    command: [ "sleep", "infinity" ]

  - name: test2
    image: helheim/test2:latest
    command: [ "sleep", "infinity" ]
